### ISSUE TITLE
NameError: name 'PUINT' is not defined

### ISSUE THREAD

**Issue by Rubiel1** [JonComo/stumbly#1]
I am trying to run it, but I get that error, did I miss something?

++++++++++++++++++++++++++++++++++

 runfile('C:/Users/FSU/Documents/Python Scripts/stumbly-master/editor.py', wdir='C:/Users/FSU/Documents/Python Scripts/stumbly-master')
Traceback (most recent call last):

  File "<ipython-input-1-30c256c8ac49>", line 1, in <module>
    runfile('C:/Users/FSU/Documents/Python Scripts/stumbly-master/editor.py', wdir='C:/Users/FSU/Documents/Python Scripts/stumbly-master')

  File "C:\Users\FSU\Anaconda2\envs\FSU\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\FSU\Anaconda2\envs\FSU\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/FSU/Documents/Python Scripts/stumbly-master/editor.py", line 1, in <module>
    from engine import Engine

  File "engine.py", line 5, in <module>
    from pyglet.window import key

  File "C:\Users\FSU\Anaconda2\envs\FSU\lib\site-packages\pyglet\window\__init__.py", line 1781, in <module>
    from pyglet.window.win32 import Win32Window as Window

  File "C:\Users\FSU\Anaconda2\envs\FSU\lib\site-packages\pyglet\window\win32\__init__.py", line 59, in <module>
    from pyglet.canvas.win32 import Win32Canvas

  File "C:\Users\FSU\Anaconda2\envs\FSU\lib\site-packages\pyglet\canvas\__init__.py", line 99, in <module>
    from pyglet.canvas.win32 import Win32Display as Display

  File "C:\Users\FSU\Anaconda2\envs\FSU\lib\site-packages\pyglet\canvas\win32.py", line 7, in <module>
    from pyglet.libs.win32 import _kernel32, _user32, types, constants

  File "C:\Users\FSU\Anaconda2\envs\FSU\lib\site-packages\pyglet\libs\win32\__init__.py", line 237, in <module>
    _user32.GetRawInputData.argtypes = [HRAWINPUT, UINT, LPVOID, PUINT, UINT]

NameError: name 'PUINT' is not defined

**Comment by Rubiel1** [comment]
I found here https://bitbucket.org/pyglet/pyglet/issues/170/nameerror-name-puint-is-not-defined that:
 The pyglet versions on pypi are missing a fix for 32-bit. To fix it for now, you can upgrade to the current development version: pip install --upgrade https://bitbucket.org/pyglet/pyglet/get/tip.zip
